name: CI/CD Pipeline - v7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pytest requests

    - name: Build Docker image
      run: |
        docker build -f Containerfile -t myapp:test .

    - name: Run Docker container
      run: |
        docker run -d -p 80:80 myapp:test
        sleep 10  # Wait for the container to be fully up and running

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest test_webserver.py

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-central-1
    
    - name: Get AWS login and pass
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ vars.AWS_REGISTRY_ID }}.dkr.ecr.eu-central-1.amazonaws.com

    - name: Build Image
      run: |
        docker build -f Dockerfile -t common_image:${{ github.sha }} .

    - name: Tag Image for Docker
      run: |
        docker tag common_image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
          
    - name: Push to Docker Hub    
      run: |  
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
  
    - name: Tag image for AWS
      run: |
        docker tag common_image:${{ github.sha }} ${{ vars.AWS_REGISTRY_ID }}.dkr.ecr.eu-central-1.amazonaws.com/${{ vars.AWS_REPOSITORY_NAME }}:latest
      
    - name: Push to AWS ECR
      run: |
        docker push ${{ vars.AWS_REGISTRY_ID }}.dkr.ecr.eu-central-1.amazonaws.com/${{ vars.AWS_REPOSITORY_NAME }}:latest
      

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Pull and run Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
